// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: hostlink/v1/hostlink.proto

package hostlinkv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentLink_Control_FullMethodName = "/hostlink.v1.AgentLink/Control"
	AgentLink_Forward_FullMethodName = "/hostlink.v1.AgentLink/Forward"
)

// AgentLinkClient is the client API for AgentLink service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentLink is the single gRPC service spanning the controller (server, public
// entrypoint) and the agent (client, behind NAT). Because under HTTP/2 a server
// cannot initiate an RPC or open a stream to a client, every "reverse" channel
// (command push, port-forward stream open) is modeled as a stream the agent
// opens and the controller drives over the response direction.
type AgentLinkClient interface {
	// Opened once after the agent connects; the controller pushes commands to the
	// agent down the response stream. All server->agent commands travel over this
	// already-open stream.
	Control(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentEvent, Command], error)
	// One per forwarded public TCP connection; opened by the agent, first frame
	// carries session_id for pairing. Internal cross-pod forwarding reuses this
	// same service definition (just dialed to a sibling pod).
	Forward(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Frame, Frame], error)
}

type agentLinkClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentLinkClient(cc grpc.ClientConnInterface) AgentLinkClient {
	return &agentLinkClient{cc}
}

func (c *agentLinkClient) Control(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentEvent, Command], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentLink_ServiceDesc.Streams[0], AgentLink_Control_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentEvent, Command]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentLink_ControlClient = grpc.BidiStreamingClient[AgentEvent, Command]

func (c *agentLinkClient) Forward(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Frame, Frame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentLink_ServiceDesc.Streams[1], AgentLink_Forward_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Frame, Frame]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentLink_ForwardClient = grpc.BidiStreamingClient[Frame, Frame]

// AgentLinkServer is the server API for AgentLink service.
// All implementations must embed UnimplementedAgentLinkServer
// for forward compatibility.
//
// AgentLink is the single gRPC service spanning the controller (server, public
// entrypoint) and the agent (client, behind NAT). Because under HTTP/2 a server
// cannot initiate an RPC or open a stream to a client, every "reverse" channel
// (command push, port-forward stream open) is modeled as a stream the agent
// opens and the controller drives over the response direction.
type AgentLinkServer interface {
	// Opened once after the agent connects; the controller pushes commands to the
	// agent down the response stream. All server->agent commands travel over this
	// already-open stream.
	Control(grpc.BidiStreamingServer[AgentEvent, Command]) error
	// One per forwarded public TCP connection; opened by the agent, first frame
	// carries session_id for pairing. Internal cross-pod forwarding reuses this
	// same service definition (just dialed to a sibling pod).
	Forward(grpc.BidiStreamingServer[Frame, Frame]) error
	mustEmbedUnimplementedAgentLinkServer()
}

// UnimplementedAgentLinkServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentLinkServer struct{}

func (UnimplementedAgentLinkServer) Control(grpc.BidiStreamingServer[AgentEvent, Command]) error {
	return status.Error(codes.Unimplemented, "method Control not implemented")
}
func (UnimplementedAgentLinkServer) Forward(grpc.BidiStreamingServer[Frame, Frame]) error {
	return status.Error(codes.Unimplemented, "method Forward not implemented")
}
func (UnimplementedAgentLinkServer) mustEmbedUnimplementedAgentLinkServer() {}
func (UnimplementedAgentLinkServer) testEmbeddedByValue()                   {}

// UnsafeAgentLinkServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentLinkServer will
// result in compilation errors.
type UnsafeAgentLinkServer interface {
	mustEmbedUnimplementedAgentLinkServer()
}

func RegisterAgentLinkServer(s grpc.ServiceRegistrar, srv AgentLinkServer) {
	// If the following call panics, it indicates UnimplementedAgentLinkServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentLink_ServiceDesc, srv)
}

func _AgentLink_Control_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentLinkServer).Control(&grpc.GenericServerStream[AgentEvent, Command]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentLink_ControlServer = grpc.BidiStreamingServer[AgentEvent, Command]

func _AgentLink_Forward_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentLinkServer).Forward(&grpc.GenericServerStream[Frame, Frame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentLink_ForwardServer = grpc.BidiStreamingServer[Frame, Frame]

// AgentLink_ServiceDesc is the grpc.ServiceDesc for AgentLink service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentLink_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hostlink.v1.AgentLink",
	HandlerType: (*AgentLinkServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Control",
			Handler:       _AgentLink_Control_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Forward",
			Handler:       _AgentLink_Forward_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "hostlink/v1/hostlink.proto",
}
