// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: hostlink/v1/hostlink.proto

package hostlinkv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentLink_Control_FullMethodName = "/hostlink.v1.AgentLink/Control"
	AgentLink_Forward_FullMethodName = "/hostlink.v1.AgentLink/Forward"
)

// AgentLinkClient is the client API for AgentLink service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentLink is the single gRPC service spanning the controller (server, public
// entrypoint) and the agent (client, behind NAT). Because under HTTP/2 a server
// cannot initiate an RPC or open a stream to a client, every "reverse" channel
// (command push, port-forward stream open) is modeled as a stream the agent
// opens and the controller drives over the response direction.
type AgentLinkClient interface {
	// Opened once after the agent connects; the controller pushes commands to the
	// agent down the response stream. All server->agent commands travel over this
	// already-open stream.
	Control(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentEvent, Command], error)
	// One per forwarded public TCP connection; opened by the agent after an
	// OpenForward command. The first frame is an OPEN frame carrying session_id
	// for pairing, or RESET (with session_id) if the container-side dial failed.
	// Cross-pod forwarding travels over ControllerPeer.Forward on the peer
	// plane instead of this agent-facing service.
	Forward(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Frame, Frame], error)
}

type agentLinkClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentLinkClient(cc grpc.ClientConnInterface) AgentLinkClient {
	return &agentLinkClient{cc}
}

func (c *agentLinkClient) Control(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentEvent, Command], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentLink_ServiceDesc.Streams[0], AgentLink_Control_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentEvent, Command]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentLink_ControlClient = grpc.BidiStreamingClient[AgentEvent, Command]

func (c *agentLinkClient) Forward(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Frame, Frame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentLink_ServiceDesc.Streams[1], AgentLink_Forward_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Frame, Frame]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentLink_ForwardClient = grpc.BidiStreamingClient[Frame, Frame]

// AgentLinkServer is the server API for AgentLink service.
// All implementations must embed UnimplementedAgentLinkServer
// for forward compatibility.
//
// AgentLink is the single gRPC service spanning the controller (server, public
// entrypoint) and the agent (client, behind NAT). Because under HTTP/2 a server
// cannot initiate an RPC or open a stream to a client, every "reverse" channel
// (command push, port-forward stream open) is modeled as a stream the agent
// opens and the controller drives over the response direction.
type AgentLinkServer interface {
	// Opened once after the agent connects; the controller pushes commands to the
	// agent down the response stream. All server->agent commands travel over this
	// already-open stream.
	Control(grpc.BidiStreamingServer[AgentEvent, Command]) error
	// One per forwarded public TCP connection; opened by the agent after an
	// OpenForward command. The first frame is an OPEN frame carrying session_id
	// for pairing, or RESET (with session_id) if the container-side dial failed.
	// Cross-pod forwarding travels over ControllerPeer.Forward on the peer
	// plane instead of this agent-facing service.
	Forward(grpc.BidiStreamingServer[Frame, Frame]) error
	mustEmbedUnimplementedAgentLinkServer()
}

// UnimplementedAgentLinkServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentLinkServer struct{}

func (UnimplementedAgentLinkServer) Control(grpc.BidiStreamingServer[AgentEvent, Command]) error {
	return status.Error(codes.Unimplemented, "method Control not implemented")
}
func (UnimplementedAgentLinkServer) Forward(grpc.BidiStreamingServer[Frame, Frame]) error {
	return status.Error(codes.Unimplemented, "method Forward not implemented")
}
func (UnimplementedAgentLinkServer) mustEmbedUnimplementedAgentLinkServer() {}
func (UnimplementedAgentLinkServer) testEmbeddedByValue()                   {}

// UnsafeAgentLinkServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentLinkServer will
// result in compilation errors.
type UnsafeAgentLinkServer interface {
	mustEmbedUnimplementedAgentLinkServer()
}

func RegisterAgentLinkServer(s grpc.ServiceRegistrar, srv AgentLinkServer) {
	// If the following call panics, it indicates UnimplementedAgentLinkServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentLink_ServiceDesc, srv)
}

func _AgentLink_Control_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentLinkServer).Control(&grpc.GenericServerStream[AgentEvent, Command]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentLink_ControlServer = grpc.BidiStreamingServer[AgentEvent, Command]

func _AgentLink_Forward_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentLinkServer).Forward(&grpc.GenericServerStream[Frame, Frame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentLink_ForwardServer = grpc.BidiStreamingServer[Frame, Frame]

// AgentLink_ServiceDesc is the grpc.ServiceDesc for AgentLink service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentLink_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hostlink.v1.AgentLink",
	HandlerType: (*AgentLinkServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Control",
			Handler:       _AgentLink_Control_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Forward",
			Handler:       _AgentLink_Forward_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "hostlink/v1/hostlink.proto",
}

const (
	ControllerPeer_Dispatch_FullMethodName       = "/hostlink.v1.ControllerPeer/Dispatch"
	ControllerPeer_DispatchStream_FullMethodName = "/hostlink.v1.ControllerPeer/DispatchStream"
	ControllerPeer_Upload_FullMethodName         = "/hostlink.v1.ControllerPeer/Upload"
	ControllerPeer_Forward_FullMethodName        = "/hostlink.v1.ControllerPeer/Forward"
)

// ControllerPeerClient is the client API for ControllerPeer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ControllerPeer is the controller<->controller (sibling pod) plane. An agent
// pins its Control stream to the one pod it dialed, but an API request (e.g.
// REST POST /agents/<id>/containers) can land on any replica behind the L4 LB.
// A pod that receives a request for an agent it does not hold relays it here to
// the holding pod (resolved via the Redis agent->pod registry); the holding pod
// drives the request over that agent's Control stream and returns the result.
type ControllerPeerClient interface {
	// Dispatch relays a single agent-targeted request to the holding pod. It is a
	// pure routing hop and does not interpret the request: method/payload are
	// opaque and travel unchanged to the agent. A pod that no longer holds the
	// agent (the mapping went stale) rejects with FAILED_PRECONDITION so the
	// caller re-resolves and retries.
	Dispatch(ctx context.Context, in *DispatchRequest, opts ...grpc.CallOption) (*AgentResult, error)
	// DispatchStream relays a streaming agent-targeted request to the holding pod.
	// Each streamed AgentResult is a progress frame except the last, which has
	// final=true and carries the terminal code/payload/error. Used for long-running
	// operations (e.g. "images.pull") that report progress before completing.
	DispatchStream(ctx context.Context, in *DispatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AgentResult], error)
	// Upload relays a streaming controller->agent request body to the holding pod.
	// The first UploadFrame carries the routing key and the opening AgentRequest
	// (e.g. an "fs.write" open); subsequent frames carry the body bytes, the last
	// marked with last=true. The holding pod drives the agent and returns the
	// terminal AgentResult. A pod that no longer holds the agent rejects with
	// FAILED_PRECONDITION so the caller re-resolves and retries.
	Upload(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadFrame, AgentResult], error)
	// Forward relays one public TCP connection's byte pipe to the holding pod.
	// The requesting pod sends an OPEN frame first (session_id + open carrying
	// the agent_id/target routing key); the holding pod pushes OpenForward to
	// the agent, pairs the agent's AgentLink.Forward stream, splices the two
	// pipes, and replies with a READY frame once the end-to-end path is
	// established, so the caller only then starts consuming the public socket.
	// A pod that no longer holds the agent rejects with FAILED_PRECONDITION so
	// the caller re-resolves the holder and retries before any public bytes
	// have been consumed.
	Forward(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Frame, Frame], error)
}

type controllerPeerClient struct {
	cc grpc.ClientConnInterface
}

func NewControllerPeerClient(cc grpc.ClientConnInterface) ControllerPeerClient {
	return &controllerPeerClient{cc}
}

func (c *controllerPeerClient) Dispatch(ctx context.Context, in *DispatchRequest, opts ...grpc.CallOption) (*AgentResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentResult)
	err := c.cc.Invoke(ctx, ControllerPeer_Dispatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerPeerClient) DispatchStream(ctx context.Context, in *DispatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AgentResult], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ControllerPeer_ServiceDesc.Streams[0], ControllerPeer_DispatchStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DispatchRequest, AgentResult]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControllerPeer_DispatchStreamClient = grpc.ServerStreamingClient[AgentResult]

func (c *controllerPeerClient) Upload(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadFrame, AgentResult], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ControllerPeer_ServiceDesc.Streams[1], ControllerPeer_Upload_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UploadFrame, AgentResult]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControllerPeer_UploadClient = grpc.ClientStreamingClient[UploadFrame, AgentResult]

func (c *controllerPeerClient) Forward(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Frame, Frame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ControllerPeer_ServiceDesc.Streams[2], ControllerPeer_Forward_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Frame, Frame]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControllerPeer_ForwardClient = grpc.BidiStreamingClient[Frame, Frame]

// ControllerPeerServer is the server API for ControllerPeer service.
// All implementations must embed UnimplementedControllerPeerServer
// for forward compatibility.
//
// ControllerPeer is the controller<->controller (sibling pod) plane. An agent
// pins its Control stream to the one pod it dialed, but an API request (e.g.
// REST POST /agents/<id>/containers) can land on any replica behind the L4 LB.
// A pod that receives a request for an agent it does not hold relays it here to
// the holding pod (resolved via the Redis agent->pod registry); the holding pod
// drives the request over that agent's Control stream and returns the result.
type ControllerPeerServer interface {
	// Dispatch relays a single agent-targeted request to the holding pod. It is a
	// pure routing hop and does not interpret the request: method/payload are
	// opaque and travel unchanged to the agent. A pod that no longer holds the
	// agent (the mapping went stale) rejects with FAILED_PRECONDITION so the
	// caller re-resolves and retries.
	Dispatch(context.Context, *DispatchRequest) (*AgentResult, error)
	// DispatchStream relays a streaming agent-targeted request to the holding pod.
	// Each streamed AgentResult is a progress frame except the last, which has
	// final=true and carries the terminal code/payload/error. Used for long-running
	// operations (e.g. "images.pull") that report progress before completing.
	DispatchStream(*DispatchRequest, grpc.ServerStreamingServer[AgentResult]) error
	// Upload relays a streaming controller->agent request body to the holding pod.
	// The first UploadFrame carries the routing key and the opening AgentRequest
	// (e.g. an "fs.write" open); subsequent frames carry the body bytes, the last
	// marked with last=true. The holding pod drives the agent and returns the
	// terminal AgentResult. A pod that no longer holds the agent rejects with
	// FAILED_PRECONDITION so the caller re-resolves and retries.
	Upload(grpc.ClientStreamingServer[UploadFrame, AgentResult]) error
	// Forward relays one public TCP connection's byte pipe to the holding pod.
	// The requesting pod sends an OPEN frame first (session_id + open carrying
	// the agent_id/target routing key); the holding pod pushes OpenForward to
	// the agent, pairs the agent's AgentLink.Forward stream, splices the two
	// pipes, and replies with a READY frame once the end-to-end path is
	// established, so the caller only then starts consuming the public socket.
	// A pod that no longer holds the agent rejects with FAILED_PRECONDITION so
	// the caller re-resolves the holder and retries before any public bytes
	// have been consumed.
	Forward(grpc.BidiStreamingServer[Frame, Frame]) error
	mustEmbedUnimplementedControllerPeerServer()
}

// UnimplementedControllerPeerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControllerPeerServer struct{}

func (UnimplementedControllerPeerServer) Dispatch(context.Context, *DispatchRequest) (*AgentResult, error) {
	return nil, status.Error(codes.Unimplemented, "method Dispatch not implemented")
}
func (UnimplementedControllerPeerServer) DispatchStream(*DispatchRequest, grpc.ServerStreamingServer[AgentResult]) error {
	return status.Error(codes.Unimplemented, "method DispatchStream not implemented")
}
func (UnimplementedControllerPeerServer) Upload(grpc.ClientStreamingServer[UploadFrame, AgentResult]) error {
	return status.Error(codes.Unimplemented, "method Upload not implemented")
}
func (UnimplementedControllerPeerServer) Forward(grpc.BidiStreamingServer[Frame, Frame]) error {
	return status.Error(codes.Unimplemented, "method Forward not implemented")
}
func (UnimplementedControllerPeerServer) mustEmbedUnimplementedControllerPeerServer() {}
func (UnimplementedControllerPeerServer) testEmbeddedByValue()                        {}

// UnsafeControllerPeerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControllerPeerServer will
// result in compilation errors.
type UnsafeControllerPeerServer interface {
	mustEmbedUnimplementedControllerPeerServer()
}

func RegisterControllerPeerServer(s grpc.ServiceRegistrar, srv ControllerPeerServer) {
	// If the following call panics, it indicates UnimplementedControllerPeerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ControllerPeer_ServiceDesc, srv)
}

func _ControllerPeer_Dispatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DispatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerPeerServer).Dispatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControllerPeer_Dispatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerPeerServer).Dispatch(ctx, req.(*DispatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerPeer_DispatchStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DispatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ControllerPeerServer).DispatchStream(m, &grpc.GenericServerStream[DispatchRequest, AgentResult]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControllerPeer_DispatchStreamServer = grpc.ServerStreamingServer[AgentResult]

func _ControllerPeer_Upload_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ControllerPeerServer).Upload(&grpc.GenericServerStream[UploadFrame, AgentResult]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControllerPeer_UploadServer = grpc.ClientStreamingServer[UploadFrame, AgentResult]

func _ControllerPeer_Forward_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ControllerPeerServer).Forward(&grpc.GenericServerStream[Frame, Frame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControllerPeer_ForwardServer = grpc.BidiStreamingServer[Frame, Frame]

// ControllerPeer_ServiceDesc is the grpc.ServiceDesc for ControllerPeer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ControllerPeer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hostlink.v1.ControllerPeer",
	HandlerType: (*ControllerPeerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Dispatch",
			Handler:    _ControllerPeer_Dispatch_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DispatchStream",
			Handler:       _ControllerPeer_DispatchStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Upload",
			Handler:       _ControllerPeer_Upload_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Forward",
			Handler:       _ControllerPeer_Forward_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "hostlink/v1/hostlink.proto",
}
