// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: hostlink/v1/hostlink.proto

package hostlinkv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Frame_Type int32

const (
	Frame_DATA       Frame_Type = 0
	Frame_HALF_CLOSE Frame_Type = 1 // sender hit local read EOF: no more data this direction
	Frame_RESET      Frame_Type = 2 // hard failure: abort both directions immediately
	Frame_OPEN       Frame_Type = 3 // first frame of a stream: pairs by session_id (+ open on the peer hop)
	Frame_READY      Frame_Type = 4 // peer-hop ack: end-to-end pipe established, safe to consume public bytes
)

// Enum value maps for Frame_Type.
var (
	Frame_Type_name = map[int32]string{
		0: "DATA",
		1: "HALF_CLOSE",
		2: "RESET",
		3: "OPEN",
		4: "READY",
	}
	Frame_Type_value = map[string]int32{
		"DATA":       0,
		"HALF_CLOSE": 1,
		"RESET":      2,
		"OPEN":       3,
		"READY":      4,
	}
)

func (x Frame_Type) Enum() *Frame_Type {
	p := new(Frame_Type)
	*p = x
	return p
}

func (x Frame_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Frame_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_hostlink_v1_hostlink_proto_enumTypes[0].Descriptor()
}

func (Frame_Type) Type() protoreflect.EnumType {
	return &file_hostlink_v1_hostlink_proto_enumTypes[0]
}

func (x Frame_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Frame_Type.Descriptor instead.
func (Frame_Type) EnumDescriptor() ([]byte, []int) {
	return file_hostlink_v1_hostlink_proto_rawDescGZIP(), []int{14, 0}
}

// AgentEvent is the agent->controller direction of the Control stream.
type AgentEvent struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	AgentId string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// Types that are valid to be assigned to Kind:
	//
	//	*AgentEvent_Hello
	//	*AgentEvent_Heartbeat
	//	*AgentEvent_Event
	//	*AgentEvent_Result
	//	*AgentEvent_Progress
	Kind          isAgentEvent_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentEvent) Reset() {
	*x = AgentEvent{}
	mi := &file_hostlink_v1_hostlink_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentEvent) ProtoMessage() {}

func (x *AgentEvent) ProtoReflect() protoreflect.Message {
	mi := &file_hostlink_v1_hostlink_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentEvent.ProtoReflect.Descriptor instead.
func (*AgentEvent) Descriptor() ([]byte, []int) {
	return file_hostlink_v1_hostlink_proto_rawDescGZIP(), []int{0}
}

func (x *AgentEvent) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentEvent) GetKind() isAgentEvent_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *AgentEvent) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Kind.(*AgentEvent_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *AgentEvent) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Kind.(*AgentEvent_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentEvent) GetEvent() *DockerEvent {
	if x != nil {
		if x, ok := x.Kind.(*AgentEvent_Event); ok {
			return x.Event
		}
	}
	return nil
}

func (x *AgentEvent) GetResult() *AgentResult {
	if x != nil {
		if x, ok := x.Kind.(*AgentEvent_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *AgentEvent) GetProgress() *AgentProgress {
	if x != nil {
		if x, ok := x.Kind.(*AgentEvent_Progress); ok {
			return x.Progress
		}
	}
	return nil
}

type isAgentEvent_Kind interface {
	isAgentEvent_Kind()
}

type AgentEvent_Hello struct {
	Hello *Hello `protobuf:"bytes,2,opt,name=hello,proto3,oneof"` // initial handshake: auth, capability declaration
}

type AgentEvent_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,3,opt,name=heartbeat,proto3,oneof"` // refresh the TTL of the agent->pod mapping in Redis
}

type AgentEvent_Event struct {
	Event *DockerEvent `protobuf:"bytes,4,opt,name=event,proto3,oneof"` // container start/stop/die reports
}

type AgentEvent_Result struct {
	Result *AgentResult `protobuf:"bytes,5,opt,name=result,proto3,oneof"` // reply to a controller->agent AgentRequest
}

type AgentEvent_Progress struct {
	Progress *AgentProgress `protobuf:"bytes,6,opt,name=progress,proto3,oneof"` // streaming progress for a long-running AgentRequest
}

func (*AgentEvent_Hello) isAgentEvent_Kind() {}

func (*AgentEvent_Heartbeat) isAgentEvent_Kind() {}

func (*AgentEvent_Event) isAgentEvent_Kind() {}

func (*AgentEvent_Result) isAgentEvent_Kind() {}

func (*AgentEvent_Progress) isAgentEvent_Kind() {}

// Hello is the first message an agent sends to authenticate and declare itself.
type Hello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_hostlink_v1_hostlink_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_hostlink_v1_hostlink_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_hostlink_v1_hostlink_proto_rawDescGZIP(), []int{1}
}

func (x *Hello) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// Heartbeat refreshes the agent->pod mapping TTL in the registry.
type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_hostlink_v1_hostlink_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_hostlink_v1_hostlink_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_hostlink_v1_hostlink_proto_rawDescGZIP(), []int{2}
}

// DockerEvent reports a local container lifecycle transition observed via the
// Docker event stream.
type DockerEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	ContainerId   string                 `protobuf:"bytes,2,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DockerEvent) Reset() {
	*x = DockerEvent{}
	mi := &file_hostlink_v1_hostlink_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DockerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DockerEvent) ProtoMessage() {}

func (x *DockerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_hostlink_v1_hostlink_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DockerEvent.ProtoReflect.Descriptor instead.
func (*DockerEvent) Descriptor() ([]byte, []int) {
	return file_hostlink_v1_hostlink_proto_rawDescGZIP(), []int{3}
}

func (x *DockerEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DockerEvent) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

// Command is the controller->agent direction of the Control stream.
type Command struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Cmd:
	//
	//	*Command_OpenForward
	//	*Command_DockerOp
	//	*Command_ExposeRule
	//	*Command_Request
	//	*Command_Chunk
	Cmd           isCommand_Cmd `protobuf_oneof:"cmd"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_hostlink_v1_hostlink_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_hostlink_v1_hostlink_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_hostlink_v1_hostlink_proto_rawDescGZIP(), []int{4}
}

func (x *Command) GetCmd() isCommand_Cmd {
	if x != nil {
		return x.Cmd
	}
	return nil
}

func (x *Command) GetOpenForward() *OpenForward {
	if x != nil {
		if x, ok := x.Cmd.(*Command_OpenForward); ok {
			return x.OpenForward
		}
	}
	return nil
}

func (x *Command) GetDockerOp() *DockerOp {
	if x != nil {
		if x, ok := x.Cmd.(*Command_DockerOp); ok {
			return x.DockerOp
		}
	}
	return nil
}

func (x *Command) GetExposeRule() *ExposeRule {
	if x != nil {
		if x, ok := x.Cmd.(*Command_ExposeRule); ok {
			return x.ExposeRule
		}
	}
	return nil
}

func (x *Command) GetRequest() *AgentRequest {
	if x != nil {
		if x, ok := x.Cmd.(*Command_Request); ok {
			return x.Request
		}
	}
	return nil
}

func (x *Command) GetChunk() *AgentRequestChunk {
	if x != nil {
		if x, ok := x.Cmd.(*Command_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isCommand_Cmd interface {
	isCommand_Cmd()
}

type Command_OpenForward struct {
	OpenForward *OpenForward `protobuf:"bytes,1,opt,name=open_forward,json=openForward,proto3,oneof"` // tell the agent to open a Forward stream for a session
}

type Command_DockerOp struct {
	DockerOp *DockerOp `protobuf:"bytes,2,opt,name=docker_op,json=dockerOp,proto3,oneof"` // run/stop/start/pause/unpause/rm
}

type Command_ExposeRule struct {
	ExposeRule *ExposeRule `protobuf:"bytes,3,opt,name=expose_rule,json=exposeRule,proto3,oneof"` // add/remove a port-exposure rule
}

type Command_Request struct {
	Request *AgentRequest `protobuf:"bytes,4,opt,name=request,proto3,oneof"` // generic API-driven request (containers/images/...)
}

type Command_Chunk struct {
	Chunk *AgentRequestChunk `protobuf:"bytes,5,opt,name=chunk,proto3,oneof"` // body chunk for a streaming request (e.g. "fs.write")
}

func (*Command_OpenForward) isCommand_Cmd() {}

func (*Command_DockerOp) isCommand_Cmd() {}

func (*Command_ExposeRule) isCommand_Cmd() {}

func (*Command_Request) isCommand_Cmd() {}

func (*Command_Chunk) isCommand_Cmd() {}

// AgentRequestChunk carries one chunk of a streaming request body for the
// AgentRequest correlated by request_id. The controller sends the opening
// AgentRequest first (method names the operation, payload its metadata), then a
// sequence of chunks; last=true marks the final one. Used for large uploads so
// the body never has to be buffered into a single message.
type AgentRequestChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Last          bool                   `protobuf:"varint,3,opt,name=last,proto3" json:"last,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentRequestChunk) Reset() {
	*x = AgentRequestChunk{}
	mi := &file_hostlink_v1_hostlink_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRequestChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRequestChunk) ProtoMessage() {}

func (x *AgentRequestChunk) ProtoReflect() protoreflect.Message {
	mi := &file_hostlink_v1_hostlink_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRequestChunk.ProtoReflect.Descriptor instead.
func (*AgentRequestChunk) Descriptor() ([]byte, []int) {
	return file_hostlink_v1_hostlink_proto_rawDescGZIP(), []int{5}
}

func (x *AgentRequestChunk) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AgentRequestChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AgentRequestChunk) GetLast() bool {
	if x != nil {
		return x.Last
	}
	return false
}

// AgentRequest is the generic, method-dispatched request the controller drives
// to an agent in response to an API call. The controller-side dispatch layer
// (and the ControllerPeer relay hop) treat method/payload as opaque: method
// names the operation (e.g. "containers.create", "images.list") and payload is
// its method-specific body, carried as raw JSON. request_id correlates the
// eventual AgentResult so a synchronous REST handler can await the reply.
type AgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"` // method-specific request body, JSON-encoded
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentRequest) Reset() {
	*x = AgentRequest{}
	mi := &file_hostlink_v1_hostlink_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRequest) ProtoMessage() {}

func (x *AgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hostlink_v1_hostlink_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRequest.ProtoReflect.Descriptor instead.
func (*AgentRequest) Descriptor() ([]byte, []int) {
	return file_hostlink_v1_hostlink_proto_rawDescGZIP(), []int{6}
}

func (x *AgentRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AgentRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *AgentRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// AgentResult is the agent's reply to an AgentRequest, correlated by
// request_id. code mirrors an HTTP status so the REST layer maps it back
// directly; payload carries the method-specific result body (JSON) and error
// holds a human-readable message when code indicates failure.
type AgentResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Code          uint32                 `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"` // method-specific result body, JSON-encoded
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	Final         bool                   `protobuf:"varint,5,opt,name=final,proto3" json:"final,omitempty"` // on a streamed reply, marks the terminal frame
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentResult) Reset() {
	*x = AgentResult{}
	mi := &file_hostlink_v1_hostlink_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentResult) ProtoMessage() {}

func (x *AgentResult) ProtoReflect() protoreflect.Message {
	mi := &file_hostlink_v1_hostlink_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentResult.ProtoReflect.Descriptor instead.
func (*AgentResult) Descriptor() ([]byte, []int) {
	return file_hostlink_v1_hostlink_proto_rawDescGZIP(), []int{7}
}

func (x *AgentResult) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AgentResult) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AgentResult) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *AgentResult) GetFinal() bool {
	if x != nil {
		return x.Final
	}
	return false
}

// AgentProgress is an intermediate, non-terminal update for a long-running
// AgentRequest, correlated by request_id. payload carries a method-specific
// progress body (JSON); the operation still completes with an AgentResult.
type AgentProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"` // method-specific progress body, JSON-encoded
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentProgress) Reset() {
	*x = AgentProgress{}
	mi := &file_hostlink_v1_hostlink_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentProgress) ProtoMessage() {}

func (x *AgentProgress) ProtoReflect() protoreflect.Message {
	mi := &file_hostlink_v1_hostlink_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentProgress.ProtoReflect.Descriptor instead.
func (*AgentProgress) Descriptor() ([]byte, []int) {
	return file_hostlink_v1_hostlink_proto_rawDescGZIP(), []int{8}
}

func (x *AgentProgress) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AgentProgress) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// DispatchRequest wraps an AgentRequest with the agent_id routing key for the
// ControllerPeer hop. The wrapped request travels unchanged to the agent; only
// the relay needs the key to resolve the holding pod.
type DispatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Request       *AgentRequest          `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispatchRequest) Reset() {
	*x = DispatchRequest{}
	mi := &file_hostlink_v1_hostlink_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchRequest) ProtoMessage() {}

func (x *DispatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hostlink_v1_hostlink_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchRequest.ProtoReflect.Descriptor instead.
func (*DispatchRequest) Descriptor() ([]byte, []int) {
	return file_hostlink_v1_hostlink_proto_rawDescGZIP(), []int{9}
}

func (x *DispatchRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *DispatchRequest) GetRequest() *AgentRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

// UploadFrame is one message of the ControllerPeer.Upload client stream. The
// first frame sets open (agent_id + the opening AgentRequest); every following
// frame carries a body chunk, the last marked with last=true. It is the cross-pod
// analogue of an AgentRequest followed by AgentRequestChunks on the Control stream.
type UploadFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*UploadFrame_Open
	//	*UploadFrame_Chunk
	Kind          isUploadFrame_Kind `protobuf_oneof:"kind"`
	Last          bool               `protobuf:"varint,3,opt,name=last,proto3" json:"last,omitempty"` // marks the final chunk frame
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFrame) Reset() {
	*x = UploadFrame{}
	mi := &file_hostlink_v1_hostlink_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFrame) ProtoMessage() {}

func (x *UploadFrame) ProtoReflect() protoreflect.Message {
	mi := &file_hostlink_v1_hostlink_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFrame.ProtoReflect.Descriptor instead.
func (*UploadFrame) Descriptor() ([]byte, []int) {
	return file_hostlink_v1_hostlink_proto_rawDescGZIP(), []int{10}
}

func (x *UploadFrame) GetKind() isUploadFrame_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *UploadFrame) GetOpen() *DispatchRequest {
	if x != nil {
		if x, ok := x.Kind.(*UploadFrame_Open); ok {
			return x.Open
		}
	}
	return nil
}

func (x *UploadFrame) GetChunk() []byte {
	if x != nil {
		if x, ok := x.Kind.(*UploadFrame_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

func (x *UploadFrame) GetLast() bool {
	if x != nil {
		return x.Last
	}
	return false
}

type isUploadFrame_Kind interface {
	isUploadFrame_Kind()
}

type UploadFrame_Open struct {
	Open *DispatchRequest `protobuf:"bytes,1,opt,name=open,proto3,oneof"` // first frame: routing key + opening AgentRequest
}

type UploadFrame_Chunk struct {
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"` // subsequent frames: body bytes
}

func (*UploadFrame_Open) isUploadFrame_Kind() {}

func (*UploadFrame_Chunk) isUploadFrame_Kind() {}

// OpenForward instructs the agent to open a Forward stream for a pending public
// connection identified by session_id, targeting a container-side address.
type OpenForward struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"` // container-side addr, e.g. 172.30.1.5:8080
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenForward) Reset() {
	*x = OpenForward{}
	mi := &file_hostlink_v1_hostlink_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenForward) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenForward) ProtoMessage() {}

func (x *OpenForward) ProtoReflect() protoreflect.Message {
	mi := &file_hostlink_v1_hostlink_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenForward.ProtoReflect.Descriptor instead.
func (*OpenForward) Descriptor() ([]byte, []int) {
	return file_hostlink_v1_hostlink_proto_rawDescGZIP(), []int{11}
}

func (x *OpenForward) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *OpenForward) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

// DockerOp carries a container lifecycle operation. spec is an opaque payload
// whose schema is defined by the op (e.g. a container create spec for "run").
type DockerOp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Op            string                 `protobuf:"bytes,1,opt,name=op,proto3" json:"op,omitempty"`
	ContainerId   string                 `protobuf:"bytes,2,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Spec          []byte                 `protobuf:"bytes,3,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DockerOp) Reset() {
	*x = DockerOp{}
	mi := &file_hostlink_v1_hostlink_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DockerOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DockerOp) ProtoMessage() {}

func (x *DockerOp) ProtoReflect() protoreflect.Message {
	mi := &file_hostlink_v1_hostlink_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DockerOp.ProtoReflect.Descriptor instead.
func (*DockerOp) Descriptor() ([]byte, []int) {
	return file_hostlink_v1_hostlink_proto_rawDescGZIP(), []int{12}
}

func (x *DockerOp) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *DockerOp) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *DockerOp) GetSpec() []byte {
	if x != nil {
		return x.Spec
	}
	return nil
}

// ExposeRule adds or removes a port-exposure mapping for a container target.
type ExposeRule struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ContainerTarget string                 `protobuf:"bytes,1,opt,name=container_target,json=containerTarget,proto3" json:"container_target,omitempty"`
	PublicPort      uint32                 `protobuf:"varint,2,opt,name=public_port,json=publicPort,proto3" json:"public_port,omitempty"`
	Remove          bool                   `protobuf:"varint,3,opt,name=remove,proto3" json:"remove,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ExposeRule) Reset() {
	*x = ExposeRule{}
	mi := &file_hostlink_v1_hostlink_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExposeRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExposeRule) ProtoMessage() {}

func (x *ExposeRule) ProtoReflect() protoreflect.Message {
	mi := &file_hostlink_v1_hostlink_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExposeRule.ProtoReflect.Descriptor instead.
func (*ExposeRule) Descriptor() ([]byte, []int) {
	return file_hostlink_v1_hostlink_proto_rawDescGZIP(), []int{13}
}

func (x *ExposeRule) GetContainerTarget() string {
	if x != nil {
		return x.ContainerTarget
	}
	return ""
}

func (x *ExposeRule) GetPublicPort() uint32 {
	if x != nil {
		return x.PublicPort
	}
	return 0
}

func (x *ExposeRule) GetRemove() bool {
	if x != nil {
		return x.Remove
	}
	return false
}

// Frame is the unit of the raw-TCP byte pipe carried over a Forward stream.
// Because a gRPC stream's own lifecycle cannot represent TCP's independent
// per-direction half-close, half-close and reset are explicit frame types.
type Frame struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // set on the first (OPEN, or failure RESET) frame, for pairing
	Type      Frame_Type             `protobuf:"varint,2,opt,name=type,proto3,enum=hostlink.v1.Frame_Type" json:"type,omitempty"`
	Data      []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"` // valid only when Type == DATA
	// Routing key set only on the OPEN frame of a cross-pod
	// ControllerPeer.Forward stream; never set on agent-facing
	// AgentLink.Forward streams.
	Open          *PeerForwardOpen `protobuf:"bytes,4,opt,name=open,proto3" json:"open,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Frame) Reset() {
	*x = Frame{}
	mi := &file_hostlink_v1_hostlink_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_hostlink_v1_hostlink_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_hostlink_v1_hostlink_proto_rawDescGZIP(), []int{14}
}

func (x *Frame) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Frame) GetType() Frame_Type {
	if x != nil {
		return x.Type
	}
	return Frame_DATA
}

func (x *Frame) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Frame) GetOpen() *PeerForwardOpen {
	if x != nil {
		return x.Open
	}
	return nil
}

// PeerForwardOpen is the routing key carried by the OPEN frame of a cross-pod
// ControllerPeer.Forward stream: which agent holds the target and which
// container-side address to dial.
type PeerForwardOpen struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"` // container-side addr, e.g. 172.30.1.5:8080
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerForwardOpen) Reset() {
	*x = PeerForwardOpen{}
	mi := &file_hostlink_v1_hostlink_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerForwardOpen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerForwardOpen) ProtoMessage() {}

func (x *PeerForwardOpen) ProtoReflect() protoreflect.Message {
	mi := &file_hostlink_v1_hostlink_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerForwardOpen.ProtoReflect.Descriptor instead.
func (*PeerForwardOpen) Descriptor() ([]byte, []int) {
	return file_hostlink_v1_hostlink_proto_rawDescGZIP(), []int{15}
}

func (x *PeerForwardOpen) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *PeerForwardOpen) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

var File_hostlink_v1_hostlink_proto protoreflect.FileDescriptor

const file_hostlink_v1_hostlink_proto_rawDesc = "" +
	"\n" +
	"\x1ahostlink/v1/hostlink.proto\x12\vhostlink.v1\"\xb3\x02\n" +
	"\n" +
	"AgentEvent\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12*\n" +
	"\x05hello\x18\x02 \x01(\v2\x12.hostlink.v1.HelloH\x00R\x05hello\x126\n" +
	"\theartbeat\x18\x03 \x01(\v2\x16.hostlink.v1.HeartbeatH\x00R\theartbeat\x120\n" +
	"\x05event\x18\x04 \x01(\v2\x18.hostlink.v1.DockerEventH\x00R\x05event\x122\n" +
	"\x06result\x18\x05 \x01(\v2\x18.hostlink.v1.AgentResultH\x00R\x06result\x128\n" +
	"\bprogress\x18\x06 \x01(\v2\x1a.hostlink.v1.AgentProgressH\x00R\bprogressB\x06\n" +
	"\x04kind\"\x1d\n" +
	"\x05Hello\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\v\n" +
	"\tHeartbeat\"D\n" +
	"\vDockerEvent\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12!\n" +
	"\fcontainer_id\x18\x02 \x01(\tR\vcontainerId\"\xb0\x02\n" +
	"\aCommand\x12=\n" +
	"\fopen_forward\x18\x01 \x01(\v2\x18.hostlink.v1.OpenForwardH\x00R\vopenForward\x124\n" +
	"\tdocker_op\x18\x02 \x01(\v2\x15.hostlink.v1.DockerOpH\x00R\bdockerOp\x12:\n" +
	"\vexpose_rule\x18\x03 \x01(\v2\x17.hostlink.v1.ExposeRuleH\x00R\n" +
	"exposeRule\x125\n" +
	"\arequest\x18\x04 \x01(\v2\x19.hostlink.v1.AgentRequestH\x00R\arequest\x126\n" +
	"\x05chunk\x18\x05 \x01(\v2\x1e.hostlink.v1.AgentRequestChunkH\x00R\x05chunkB\x05\n" +
	"\x03cmd\"Z\n" +
	"\x11AgentRequestChunk\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x12\n" +
	"\x04last\x18\x03 \x01(\bR\x04last\"_\n" +
	"\fAgentRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"\x86\x01\n" +
	"\vAgentResult\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x12\n" +
	"\x04code\x18\x02 \x01(\rR\x04code\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12\x14\n" +
	"\x05final\x18\x05 \x01(\bR\x05final\"H\n" +
	"\rAgentProgress\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"a\n" +
	"\x0fDispatchRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x123\n" +
	"\arequest\x18\x02 \x01(\v2\x19.hostlink.v1.AgentRequestR\arequest\"u\n" +
	"\vUploadFrame\x122\n" +
	"\x04open\x18\x01 \x01(\v2\x1c.hostlink.v1.DispatchRequestH\x00R\x04open\x12\x16\n" +
	"\x05chunk\x18\x02 \x01(\fH\x00R\x05chunk\x12\x12\n" +
	"\x04last\x18\x03 \x01(\bR\x04lastB\x06\n" +
	"\x04kind\"D\n" +
	"\vOpenForward\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\"Q\n" +
	"\bDockerOp\x12\x0e\n" +
	"\x02op\x18\x01 \x01(\tR\x02op\x12!\n" +
	"\fcontainer_id\x18\x02 \x01(\tR\vcontainerId\x12\x12\n" +
	"\x04spec\x18\x03 \x01(\fR\x04spec\"p\n" +
	"\n" +
	"ExposeRule\x12)\n" +
	"\x10container_target\x18\x01 \x01(\tR\x0fcontainerTarget\x12\x1f\n" +
	"\vpublic_port\x18\x02 \x01(\rR\n" +
	"publicPort\x12\x16\n" +
	"\x06remove\x18\x03 \x01(\bR\x06remove\"\xdb\x01\n" +
	"\x05Frame\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12+\n" +
	"\x04type\x18\x02 \x01(\x0e2\x17.hostlink.v1.Frame.TypeR\x04type\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x120\n" +
	"\x04open\x18\x04 \x01(\v2\x1c.hostlink.v1.PeerForwardOpenR\x04open\"@\n" +
	"\x04Type\x12\b\n" +
	"\x04DATA\x10\x00\x12\x0e\n" +
	"\n" +
	"HALF_CLOSE\x10\x01\x12\t\n" +
	"\x05RESET\x10\x02\x12\b\n" +
	"\x04OPEN\x10\x03\x12\t\n" +
	"\x05READY\x10\x04\"D\n" +
	"\x0fPeerForwardOpen\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target2\x80\x01\n" +
	"\tAgentLink\x12<\n" +
	"\aControl\x12\x17.hostlink.v1.AgentEvent\x1a\x14.hostlink.v1.Command(\x010\x01\x125\n" +
	"\aForward\x12\x12.hostlink.v1.Frame\x1a\x12.hostlink.v1.Frame(\x010\x012\x97\x02\n" +
	"\x0eControllerPeer\x12B\n" +
	"\bDispatch\x12\x1c.hostlink.v1.DispatchRequest\x1a\x18.hostlink.v1.AgentResult\x12J\n" +
	"\x0eDispatchStream\x12\x1c.hostlink.v1.DispatchRequest\x1a\x18.hostlink.v1.AgentResult0\x01\x12>\n" +
	"\x06Upload\x12\x18.hostlink.v1.UploadFrame\x1a\x18.hostlink.v1.AgentResult(\x01\x125\n" +
	"\aForward\x12\x12.hostlink.v1.Frame\x1a\x12.hostlink.v1.Frame(\x010\x01B?Z=github.com/humble-mun/hostlink/pkg/api/hostlink/v1;hostlinkv1b\x06proto3"

var (
	file_hostlink_v1_hostlink_proto_rawDescOnce sync.Once
	file_hostlink_v1_hostlink_proto_rawDescData []byte
)

func file_hostlink_v1_hostlink_proto_rawDescGZIP() []byte {
	file_hostlink_v1_hostlink_proto_rawDescOnce.Do(func() {
		file_hostlink_v1_hostlink_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hostlink_v1_hostlink_proto_rawDesc), len(file_hostlink_v1_hostlink_proto_rawDesc)))
	})
	return file_hostlink_v1_hostlink_proto_rawDescData
}

var file_hostlink_v1_hostlink_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_hostlink_v1_hostlink_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_hostlink_v1_hostlink_proto_goTypes = []any{
	(Frame_Type)(0),           // 0: hostlink.v1.Frame.Type
	(*AgentEvent)(nil),        // 1: hostlink.v1.AgentEvent
	(*Hello)(nil),             // 2: hostlink.v1.Hello
	(*Heartbeat)(nil),         // 3: hostlink.v1.Heartbeat
	(*DockerEvent)(nil),       // 4: hostlink.v1.DockerEvent
	(*Command)(nil),           // 5: hostlink.v1.Command
	(*AgentRequestChunk)(nil), // 6: hostlink.v1.AgentRequestChunk
	(*AgentRequest)(nil),      // 7: hostlink.v1.AgentRequest
	(*AgentResult)(nil),       // 8: hostlink.v1.AgentResult
	(*AgentProgress)(nil),     // 9: hostlink.v1.AgentProgress
	(*DispatchRequest)(nil),   // 10: hostlink.v1.DispatchRequest
	(*UploadFrame)(nil),       // 11: hostlink.v1.UploadFrame
	(*OpenForward)(nil),       // 12: hostlink.v1.OpenForward
	(*DockerOp)(nil),          // 13: hostlink.v1.DockerOp
	(*ExposeRule)(nil),        // 14: hostlink.v1.ExposeRule
	(*Frame)(nil),             // 15: hostlink.v1.Frame
	(*PeerForwardOpen)(nil),   // 16: hostlink.v1.PeerForwardOpen
}
var file_hostlink_v1_hostlink_proto_depIdxs = []int32{
	2,  // 0: hostlink.v1.AgentEvent.hello:type_name -> hostlink.v1.Hello
	3,  // 1: hostlink.v1.AgentEvent.heartbeat:type_name -> hostlink.v1.Heartbeat
	4,  // 2: hostlink.v1.AgentEvent.event:type_name -> hostlink.v1.DockerEvent
	8,  // 3: hostlink.v1.AgentEvent.result:type_name -> hostlink.v1.AgentResult
	9,  // 4: hostlink.v1.AgentEvent.progress:type_name -> hostlink.v1.AgentProgress
	12, // 5: hostlink.v1.Command.open_forward:type_name -> hostlink.v1.OpenForward
	13, // 6: hostlink.v1.Command.docker_op:type_name -> hostlink.v1.DockerOp
	14, // 7: hostlink.v1.Command.expose_rule:type_name -> hostlink.v1.ExposeRule
	7,  // 8: hostlink.v1.Command.request:type_name -> hostlink.v1.AgentRequest
	6,  // 9: hostlink.v1.Command.chunk:type_name -> hostlink.v1.AgentRequestChunk
	7,  // 10: hostlink.v1.DispatchRequest.request:type_name -> hostlink.v1.AgentRequest
	10, // 11: hostlink.v1.UploadFrame.open:type_name -> hostlink.v1.DispatchRequest
	0,  // 12: hostlink.v1.Frame.type:type_name -> hostlink.v1.Frame.Type
	16, // 13: hostlink.v1.Frame.open:type_name -> hostlink.v1.PeerForwardOpen
	1,  // 14: hostlink.v1.AgentLink.Control:input_type -> hostlink.v1.AgentEvent
	15, // 15: hostlink.v1.AgentLink.Forward:input_type -> hostlink.v1.Frame
	10, // 16: hostlink.v1.ControllerPeer.Dispatch:input_type -> hostlink.v1.DispatchRequest
	10, // 17: hostlink.v1.ControllerPeer.DispatchStream:input_type -> hostlink.v1.DispatchRequest
	11, // 18: hostlink.v1.ControllerPeer.Upload:input_type -> hostlink.v1.UploadFrame
	15, // 19: hostlink.v1.ControllerPeer.Forward:input_type -> hostlink.v1.Frame
	5,  // 20: hostlink.v1.AgentLink.Control:output_type -> hostlink.v1.Command
	15, // 21: hostlink.v1.AgentLink.Forward:output_type -> hostlink.v1.Frame
	8,  // 22: hostlink.v1.ControllerPeer.Dispatch:output_type -> hostlink.v1.AgentResult
	8,  // 23: hostlink.v1.ControllerPeer.DispatchStream:output_type -> hostlink.v1.AgentResult
	8,  // 24: hostlink.v1.ControllerPeer.Upload:output_type -> hostlink.v1.AgentResult
	15, // 25: hostlink.v1.ControllerPeer.Forward:output_type -> hostlink.v1.Frame
	20, // [20:26] is the sub-list for method output_type
	14, // [14:20] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_hostlink_v1_hostlink_proto_init() }
func file_hostlink_v1_hostlink_proto_init() {
	if File_hostlink_v1_hostlink_proto != nil {
		return
	}
	file_hostlink_v1_hostlink_proto_msgTypes[0].OneofWrappers = []any{
		(*AgentEvent_Hello)(nil),
		(*AgentEvent_Heartbeat)(nil),
		(*AgentEvent_Event)(nil),
		(*AgentEvent_Result)(nil),
		(*AgentEvent_Progress)(nil),
	}
	file_hostlink_v1_hostlink_proto_msgTypes[4].OneofWrappers = []any{
		(*Command_OpenForward)(nil),
		(*Command_DockerOp)(nil),
		(*Command_ExposeRule)(nil),
		(*Command_Request)(nil),
		(*Command_Chunk)(nil),
	}
	file_hostlink_v1_hostlink_proto_msgTypes[10].OneofWrappers = []any{
		(*UploadFrame_Open)(nil),
		(*UploadFrame_Chunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hostlink_v1_hostlink_proto_rawDesc), len(file_hostlink_v1_hostlink_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_hostlink_v1_hostlink_proto_goTypes,
		DependencyIndexes: file_hostlink_v1_hostlink_proto_depIdxs,
		EnumInfos:         file_hostlink_v1_hostlink_proto_enumTypes,
		MessageInfos:      file_hostlink_v1_hostlink_proto_msgTypes,
	}.Build()
	File_hostlink_v1_hostlink_proto = out.File
	file_hostlink_v1_hostlink_proto_goTypes = nil
	file_hostlink_v1_hostlink_proto_depIdxs = nil
}
